// Code generated by go-swagger; DO NOT EDIT.

// Package restapi access
//
//  API for accessing github.com/practable/jump websocket ssh relay
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /api/v1
//  Version: 0.4
//  Contact: Timothy Drysdale<timothy.d.drysdale@gmail.com> https://github.com/practable
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
