// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for accessing github.com/practable/jump websocket ssh relay",
    "title": "access",
    "contact": {
      "name": "Timothy Drysdale",
      "url": "https://github.com/practable",
      "email": "timothy.d.drysdale@gmail.com"
    },
    "version": "0.4"
  },
  "host": "localhost",
  "basePath": "/api/v1",
  "paths": {
    "/connect/{host_id}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Request a websocket connection for host specified by host_id.",
        "produces": [
          "application/json"
        ],
        "summary": "request a websocket connection for host specified by host_id",
        "operationId": "connect",
        "parameters": [
          {
            "type": "string",
            "description": "Jump host identification code",
            "name": "host_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "object",
              "properties": {
                "uri": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "application/json": {
                "uri": "wss://example.com/jump/connect/host123?code=8b4f378e-6edc-42d5-b497-0f6d32ad8be3"
              }
            }
          },
          "400": {
            "description": "BadRequest",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "API for accessing github.com/practable/jump websocket ssh relay",
    "title": "access",
    "contact": {
      "name": "Timothy Drysdale",
      "url": "https://github.com/practable",
      "email": "timothy.d.drysdale@gmail.com"
    },
    "version": "0.4"
  },
  "host": "localhost",
  "basePath": "/api/v1",
  "paths": {
    "/connect/{host_id}": {
      "post": {
        "security": [
          {
            "Bearer": []
          }
        ],
        "description": "Request a websocket connection for host specified by host_id.",
        "produces": [
          "application/json"
        ],
        "summary": "request a websocket connection for host specified by host_id",
        "operationId": "connect",
        "parameters": [
          {
            "type": "string",
            "description": "Jump host identification code",
            "name": "host_id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": {
              "type": "object",
              "properties": {
                "uri": {
                  "type": "string"
                }
              }
            },
            "examples": {
              "application/json": {
                "uri": "wss://example.com/jump/connect/host123?code=8b4f378e-6edc-42d5-b497-0f6d32ad8be3"
              }
            }
          },
          "400": {
            "description": "BadRequest",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          },
          "500": {
            "description": "Internal Error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "Bearer": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  }
}`))
}
