// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ConnectHandlerFunc turns a function with the right signature into a connect handler
type ConnectHandlerFunc func(ConnectParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ConnectHandlerFunc) Handle(params ConnectParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ConnectHandler interface for that can handle valid connect params
type ConnectHandler interface {
	Handle(ConnectParams, interface{}) middleware.Responder
}

// NewConnect creates a new http.Handler for the connect operation
func NewConnect(ctx *middleware.Context, handler ConnectHandler) *Connect {
	return &Connect{Context: ctx, Handler: handler}
}

/* Connect swagger:route POST /connect/{host_id} connect

request a websocket connection for host specified by host_id

Request a websocket connection for host specified by host_id.

*/
type Connect struct {
	Context *middleware.Context
	Handler ConnectHandler
}

func (o *Connect) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewConnectParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// ConnectOKBody connect o k body
//
// swagger:model ConnectOKBody
type ConnectOKBody struct {

	// uri
	URI string `json:"uri,omitempty"`
}

// Validate validates this connect o k body
func (o *ConnectOKBody) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this connect o k body based on context it is used
func (o *ConnectOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ConnectOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ConnectOKBody) UnmarshalBinary(b []byte) error {
	var res ConnectOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
